[fix] Ensure `gc: response-time` works on Java11 (#370)
## Before this PR

If you configured a service to use the 'response-time' GC options, the service won't start up on OpenJdk11 as [UseParNewGC was removed in Java 10](https://bugs.openjdk.java.net/browse/JDK-8173421).

```gradle
distribution {
    serviceName 'your-service'
    mainClass 'com.palantir.service.Main'
    gc 'response-time'
}
```

```
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

cc @robert3005 

## After this PR

The service should start up.